
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/group11?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



#spring:
#  redis:
#    database: 0
#    port: 3306
#    host: 127.0.0.1
#    password: 123456
#    lettuce:
#      pool:
#        max-idle: 8
#        max-active: 8
#        min-idle: 0

